In [4]:
1 + 1 //zz

NameError: name 'zz' is not defined

In [5]:
1 + 1 # zz

2

In [6]:
# 다음은 더하기
ㅋㅋ

NameError: name 'ᄏᄏ' is not defined

In [7]:
for i in range(3):
    print(i)

0
1
2


In [8]:
'abc'

'abc'

In [9]:
'''zzz'''

'zzz'

In [10]:
"""zzz"""

'zzz'

In [11]:
'it\'s mine'

"it's mine"

In [12]:
"""it's mine"""

"it's mine"

In [13]:
'''it'''s mine

SyntaxError: invalid syntax (235935799.py, line 1)

In [14]:
aa = [1,2,3]
type(aa)

list

In [15]:
a = 1

In [16]:
type(a)

int

In [17]:
import numpy as np

In [18]:
np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [19]:
np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [20]:
listt = [1,2,3,4,5]

In [21]:
print(listt[1,3,5])

TypeError: list indices must be integers or slices, not tuple

In [22]:
[1,2,3] = np.array()

SyntaxError: cannot assign to literal (4129577375.py, line 1)

In [23]:
np.array([1,2,3])

array([1, 2, 3])

In [24]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [25]:
np.array([1,2,3,4]).reshape((2,2))

array([[1, 2],
       [3, 4]])

In [26]:
array = np.array([[1,2,3],[4,5,6]])

In [27]:
    array.ndim

2

In [28]:
array.shape

(2, 3)

In [29]:
array.sum()

21

In [30]:
len(array)

2

In [31]:
import pandas as pd

In [32]:
ser = pd.Series([1,2,3])

In [33]:
ser

0    1
1    2
2    3
dtype: int64

In [34]:
ser.values

array([1, 2, 3], dtype=int64)

In [35]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [36]:
ser.sum()

6

In [37]:
ser.min()

1

In [38]:
ser = pd.Series([1,2,3], [-1,-2,-3])

In [39]:
ser.min()

1

In [40]:
ser

-1    1
-2    2
-3    3
dtype: int64

In [41]:
ser = pd.Series([2,4,4,6,7,9])

In [42]:
ser.idxMax()

AttributeError: 'Series' object has no attribute 'idxMax'

In [43]:
ser.idxmax()

5

In [44]:
ser.isin([6,7])

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [45]:
df = pd.DataFrame([[1,2,2], [3,3,4]])

In [46]:
df

0  1  2
0  1  2  2
1  3  3  4

In [47]:
df[0][0]

1

In [48]:
df[1][0]

2

In [49]:
df[1][-1]

KeyError: -1

In [50]:
dff = pd.DataFrame({"v1":[1,4], "v2":[2,5], "v3":[3,6]})

In [51]:
dff

v1  v2  v3
0   1   2   3
1   4   5   6

In [52]:
from sklearn.model_selection import train_test_split

In [54]:
df = pd.read_csv("data/bike.csv")

In [55]:
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [66]:
df.sample(n = 2)

datetime  season  holiday  workingday  weather   temp  atemp  \
6376  2012-03-02 22:00:00       1        0           1        2  14.76  18.94   
9226  2012-09-07 19:00:00       3        0           1        1  30.34  34.09   

      humidity  windspeed  casual  registered  count  
6376        87     0.0000       6          69     75  
9226        62    19.0012      70         498    568

In [71]:
df.sample(n = 2, random_state=123)

datetime  season  holiday  workingday  weather   temp  atemp  \
6495  2012-03-07 21:00:00       1        0           1        1  18.04  21.97   
7050  2012-04-12 03:00:00       2        0           1        1  13.12  15.15   

      humidity  windspeed  casual  registered  count  
6495        62    16.9979      11         177    188  
7050        61    16.9979       2           3      5

In [72]:
df["season"].unique()

array([1, 2, 3, 4], dtype=int64)

In [73]:
print(len(df["season"].unique()))

4


In [74]:
df.groupby("season").sample(n=2)

datetime  season  holiday  workingday  weather   temp  \
5940  2012-02-03 17:00:00       1        0           1        1  16.40   
726   2011-02-13 15:00:00       1        0           0        2  16.40   
7777  2012-06-04 10:00:00       2        0           1        1  26.24   
7073  2012-04-13 02:00:00       2        0           1        1  13.94   
8430  2012-07-12 15:00:00       3        0           1        1  32.80   
9497  2012-09-19 02:00:00       3        0           1        2  22.14   
4569  2011-11-03 11:00:00       4        0           1        1  18.04   
4179  2011-10-06 04:00:00       4        0           1        1  18.04   

       atemp  humidity  windspeed  casual  registered  count  
5940  20.455        37     6.0032      30         458    488  
726   20.455        30    19.9995      40         122    162  
7777  31.060        41    31.0009      67         120    187  
7073  16.665        49    12.9980       6           5     11  
8430  35.605        36    12.9980      63         208    271  
9497  25.760        64    22.0028       0           3      3  
4569  21.970        67    12.9980      12         108    120  
4179  21.970        62    19.0012       0           5      5

In [75]:
df.sample(frac=0.005)

datetime  season  holiday  workingday  weather   temp  \
6311   2012-02-19 05:00:00       1        0           0        2  10.66   
4461   2011-10-17 22:00:00       4        0           1        1  20.50   
9856   2012-10-15 01:00:00       4        0           1        2  23.78   
8444   2012-07-13 05:00:00       3        0           1        2  27.06   
7263   2012-05-02 00:00:00       2        0           1        1  24.60   
2758   2011-07-03 20:00:00       3        0           0        3  27.06   
8105   2012-06-18 02:00:00       2        0           1        1  22.14   
5388   2011-12-18 14:00:00       4        0           0        1  12.30   
6125   2012-02-11 11:00:00       1        0           0        2   9.84   
900    2011-03-01 23:00:00       1        0           1        1   9.84   
2066   2011-05-13 00:00:00       2        0           1        2  21.32   
126    2011-01-06 12:00:00       1        0           1        1  10.66   
9578   2012-10-03 11:00:00       4        0           1        1  27.06   
8787   2012-08-08 12:00:00       3        0           1        2  32.80   
10268  2012-11-13 06:00:00       4        0           1        3  13.12   
10704  2012-12-12 10:00:00       4        0           1        2  12.30   
277    2011-01-13 00:00:00       1        0           1        1   5.74   
7146   2012-04-16 03:00:00       2        1           0        1  23.78   
8710   2012-08-05 07:00:00       3        0           0        1  30.34   
9513   2012-09-19 18:00:00       3        0           1        1  23.78   
3706   2011-09-05 08:00:00       3        1           0        2  27.06   
6348   2012-03-01 18:00:00       1        0           1        1  22.14   
9623   2012-10-05 08:00:00       4        0           1        1  23.78   
9940   2012-10-18 13:00:00       4        0           1        1  25.42   
4195   2011-10-06 20:00:00       4        0           1        1  20.50   
269    2011-01-12 16:00:00       1        0           1        1   9.02   
1412   2011-04-04 17:00:00       2        0           1        1  30.34   
8897   2012-08-13 02:00:00       3        0           1        1  26.24   
7880   2012-06-08 17:00:00       2        0           1        1  31.16   
8752   2012-08-07 01:00:00       3        0           1        1  28.70   
4678   2011-11-08 00:00:00       4        0           1        1  13.94   
9091   2012-09-02 04:00:00       3        0           0        1  27.06   
551    2011-02-06 03:00:00       1        0           0        1  10.66   
5611   2012-01-08 22:00:00       1        0           0        1  10.66   
7717   2012-06-01 22:00:00       2        0           1        3  24.60   
779    2011-02-15 21:00:00       1        0           1        1   9.84   
9817   2012-10-13 10:00:00       4        0           0        1  16.40   
10692  2012-12-11 22:00:00       4        0           1        1  12.30   
2970   2011-07-12 16:00:00       3        0           1        1  35.26   
330    2011-01-15 06:00:00       1        0           0        1   5.74   
7094   2012-04-13 23:00:00       2        0           1        1  17.22   
5337   2011-12-16 11:00:00       4        0           1        2  13.94   
8607   2012-08-01 00:00:00       3        0           1        1  27.88   
2920   2011-07-10 14:00:00       3        0           0        1  33.62   
6052   2012-02-08 10:00:00       1        0           1        2  10.66   
6569   2012-03-10 23:00:00       1        0           0        1  10.66   
10195  2012-11-10 05:00:00       4        0           0        1  11.48   
1601   2011-04-12 15:00:00       2        0           1        2  19.68   
2304   2011-06-03 22:00:00       2        0           1        1  25.42   
1522   2011-04-09 07:00:00       2        0           0        2  12.30   
1800   2011-05-01 22:00:00       2        0           0        2  18.86   
152    2011-01-07 15:00:00       1        0           1        2   8.20   
1117   2011-03-11 05:00:00       1        0

In [76]:
df_train, df_test = train_test_split(df, train=0.7, random_state=123)
df_train.head(2)

TypeError: train_test_split() got an unexpected keyword argument 'train'

In [77]:
df_train, df_test = train_test_split(df, train_size=0.7, random_state=123)
df_train.head(2)

datetime  season  holiday  workingday  weather   temp  \
4046  2011-09-19 15:00:00       3        0           1        2  24.60   
9262  2012-09-09 07:00:00       3        0           0        1  22.14   

       atemp  humidity  windspeed  casual  registered  count  
4046  30.305        60    15.0013      44         143    187  
9262  25.760        73    11.0014      20          50     70

In [78]:
df.sample(frac=0.0123).shape[0]

134

In [79]:
len(df.sample(frac=0.0123))

134

In [80]:
train, test = train_test_split(df, train_size=0.8, random_state=123)

In [82]:
max(train["temp"])

41.0

In [83]:
train["temp"].max()

41.0

In [84]:
df = pd.read_csv("data/bike.csv")

In [85]:
train, test = train_test_split(df, train_size=0.8, random_state=123)

In [86]:
train["temp"].max

<bound method NDFrame._add_numeric_operations.<locals>.max of 9395    27.06
8023    29.52
1503    15.58
493      9.02
6317    10.66
        ...  
9785    16.40
7763    27.06
5218    10.66
1346    12.30
3582    26.24
Name: temp, Length: 8708, dtype: float64>

In [87]:
max(train["temp"])

41.0

In [88]:
test["temp"].max()

39.36

In [89]:
###### ch06

In [90]:
df = pd.read_csv("data/iris_missing.csv")

In [91]:
df

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          NaN           NaN          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2        NaN
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2        NaN
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           NaN          2.5           NaN          NaN  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

[150 rows x 5 columns]

In [92]:
df_na = df.head(7)

In [93]:
df_na["Sepal_Length"].isna()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
Name: Sepal_Length, dtype: bool

In [94]:
df_na.isna()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width  Species
0         False         True          True        False    False
1         False        False         False        False    False
2         False        False         False        False     True
3         False        False         False        False    False
4         False        False         False        False     True
5         False        False         False        False    False
6          True         True          True         True    False

In [95]:
df_na.isna().sum() # 각 변수별 결측치 개수

Sepal_Length    1
Sepal_Width     2
Petal_Length    2
Petal_Width     1
Species         2
dtype: int64

In [96]:
df_na.isna().sum(axis = 1) # 각 로우별 결측치 개수

0    2
1    0
2    1
3    0
4    1
5    0
6    4
dtype: int64

In [97]:
df_na.fillna(value = {"Sepal_Length" : 999, "Sepal_Width":999})

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1        999.0           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2     NaN
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2     NaN
5           5.4          3.9           1.7          0.4  setosa
6         999.0        999.0           NaN          NaN  setosa

In [98]:
df_na.fillna(999)

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1        999.0         999.0          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2     999
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2     999
5           5.4          3.9           1.7          0.4  setosa
6         999.0        999.0         999.0        999.0  setosa

In [99]:
df_na["Sepal_Width"].mean()

3.3600000000000003

In [100]:
df_na = df_na.fillna(df_na.mean)

In [101]:
df_na = 

Sepal_Length  \
0                                                5.1   
1                                                4.9   
2                                                4.7   
3                                                4.6   
4                                                5.0   
5                                                5.4   
6  <bound method NDFrame._add_numeric_operations....   

                                         Sepal_Width  \
0  <bound method NDFrame._add_numeric_operations....   
1                                                3.0   
2                                                3.2   
3                                                3.1   
4                                                3.6   
5                                                3.9   
6  <bound method NDFrame._add_numeric_operations....   

                                        Petal_Length  \
0  <bound method NDFrame._add_numeric_operations....   
1                                                1.4   
2                                                1.3   
3                                                1.5   
4                                                1.4   
5                                                1.7   
6  <bound method NDFrame._add_numeric_operations....   

                                         Petal_Width  \
0                                                0.2   
1                                                0.2   
2                                                0.2   
3                                                0.2   
4                                                0.2   
5                                                0.4   
6  <bound method NDFrame._add_numeric_operations....   

                                             Species  
0                                             setosa  
1                                             setosa  
2  <bound method NDFrame._add_numeric_operations....  
3                                             setosa  
4  <bound method NDFrame._add_numeric_operations....  
5                                             setosa  
6                                             setosa

In [102]:
df = pd.read_csv("data/iris_missing.csv")

In [103]:
df_na = df.head(7)

In [104]:
df_na.dropna()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
1           4.9          3.0           1.4          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa

In [105]:
df_na.iloc[:,:-1].dropna(how="all")

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0           5.1          NaN           NaN          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
5           5.4          3.9           1.7          0.4

In [106]:
df["Sepal_Length"].max()

7.9

In [107]:
df["Sepal_Length"].mean()

5.853846153846154

In [108]:
df["Sepal_Length"].min()

4.3

In [109]:
df["Sepal_Length"].quantile()

5.8

In [110]:
df["Sepal_Length"].quantile(q = 0.25)

5.1

In [111]:
 df["Sepal_Width"].fillna(df["Sepal_Width"].mean()).var()

0.17561945818840946

In [112]:
df = pd.read_csv("data/iris.csv")

In [115]:
mean = df["Sepal.Length"].mean()

In [117]:
std = df["Sepal.Length"].std()

In [118]:
c1 = df["Sepal.Length"] < (mean - 1.5 * std)

In [119]:
c2 = df["Sepal.Length"] > (mean + 1.5 * std)

In [120]:
c1

0      False
1      False
2      False
3       True
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Name: Sepal.Length, Length: 150, dtype: bool

In [121]:
df

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [122]:
c2

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Name: Sepal.Length, Length: 150, dtype: bool

In [123]:
len(df.loc[c1|c2])

21

In [124]:
## ch07

In [125]:
df["is_setosa"] = np.where(df["Species"] == "setosa", 1, 0)

In [126]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  is_setosa
0           5.1          3.5           1.4          0.2  setosa          1
1           4.9          3.0           1.4          0.2  setosa          1
2           4.7          3.2           1.3          0.2  setosa          1
3           4.6          3.1           1.5          0.2  setosa          1
4           5.0          3.6           1.4          0.2  setosa          1

In [127]:
df.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species  \
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     is_setosa  
145          0  
146          0  
147          0  
148          0  
149          0

In [128]:
pd.crosstab(df["Species"], df["is_setosa"])

is_setosa    0   1
Species           
setosa       0  50
versicolor  50   0
virginica   50   0

In [129]:
df.rename(columns={"Sepal.Length" : "SL"})

SL  Sepal.Width  Petal.Length  Petal.Width    Species  is_setosa
0    5.1          3.5           1.4          0.2     setosa          1
1    4.9          3.0           1.4          0.2     setosa          1
2    4.7          3.2           1.3          0.2     setosa          1
3    4.6          3.1           1.5          0.2     setosa          1
4    5.0          3.6           1.4          0.2     setosa          1
..   ...          ...           ...          ...        ...        ...
145  6.7          3.0           5.2          2.3  virginica          0
146  6.3          2.5           5.0          1.9  virginica          0
147  6.5          3.0           5.2          2.0  virginica          0
148  6.2          3.4           5.4          2.3  virginica          0
149  5.9          3.0           5.1          1.8  virginica          0

[150 rows x 6 columns]

In [130]:
bike = pd.read_csv("data/bike.csv")

In [131]:
bike.columns

Index(['datetime', 'season', 'holiday', 'workingday', 'weather', 'temp',
       'atemp', 'humidity', 'windspeed', 'casual', 'registered', 'count'],
      dtype='object')

In [132]:
bike_sub = bike.iloc[:4, 9:11]

In [133]:
bike_sub

casual  registered
0       3          13
1       8          32
2       5          27
3       3          10

In [134]:
 bike_casual = bike["casual"]

In [135]:
bike_casual

0         3
1         8
2         5
3         3
4         0
         ..
10881     7
10882    10
10883     4
10884    12
10885     4
Name: casual, Length: 10886, dtype: int64

In [136]:
len(bike_casual > 25)

10886

In [137]:
 bike_casual = bike["casual"] > 25

In [138]:
bike_casual.length

AttributeError: 'Series' object has no attribute 'length'

In [139]:
bike_casual

0        False
1        False
2        False
3        False
4        False
         ...  
10881    False
10882    False
10883    False
10884    False
10885    False
Name: casual, Length: 10886, dtype: bool

In [140]:
len(bike_casual)

10886

In [141]:
len(bike_casual == True)

10886